apiVersion: 1
deleteDatasources:
  - name: 'Prometheus'
    orgId: 1
prune: true

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
